# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

#Exclude osx + bioc-devel as suggested here: https://github.com/irenecrsn/gmat/issues/5
#Also exclude linux + bioc-devel due to incompatibilities betwen R and BioC versions
matrix:
  include:
    - os: linux
      r: bioc-release
    - os: osx
      r: bioc-release

bioc_packages:
  - GenomeInfoDbData
  - TxDb.Athaliana.BioMart.plantsmart25

r_packages:
  - covr

# Strict checks
warnings_are_errors: true

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
