# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - bioc-release
  - bioc-devel

bioc_packages:
  - GenomeInfoDbData
  - TxDb.Athaliana.BioMart.plantsmart25

r_packages:
  - covr

# Strict checks
warnings_are_errors: true

os:
  - linux
  - osx

#Fix this issue: https://github.com/travis-ci/travis-ci/issues/10295
fortran: false

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
