# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r: bioc-release
#use_bioc: true

bioc_packages:
  - GenomeInfoDbData
  - TxDb.Athaliana.BioMart.plantsmart25

# Strict checks
warnings_are_errors: true

os:
  - linux
  - osx

